spring.application.name=moreno
spring.datasource.url=jdbc:postgresql://${SUPABASE_DB_HOST}:${SUPABASE_DB_PORT:5432}/${SUPABASE_DB_NAME:postgres}?user=${SUPABASE_DB_USER}&password=${SUPABASE_DB_PASSWORD}&sslmode=${SUPABASE_DB_SSLMODE:require}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.profiles.default=supabase
